// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAho0q-4xePePEr2OfJL3_wgc3cBpmbiqk',
    appId: '1:620043907346:web:3e4a109150112aa28843cb',
    messagingSenderId: '620043907346',
    projectId: 'flutter-test-3a45f',
    authDomain: 'flutter-test-3a45f.firebaseapp.com',
    storageBucket: 'flutter-test-3a45f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9u6UBsA1uRngsPDJ1fbPCPCOHbDb5euI',
    appId: '1:620043907346:android:a90e2a917c273d688843cb',
    messagingSenderId: '620043907346',
    projectId: 'flutter-test-3a45f',
    storageBucket: 'flutter-test-3a45f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcAPmN0FXo-zhdFLVgzwkW3ItovhbjSN8',
    appId: '1:620043907346:ios:c7f67d95cf23b7ba8843cb',
    messagingSenderId: '620043907346',
    projectId: 'flutter-test-3a45f',
    storageBucket: 'flutter-test-3a45f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcAPmN0FXo-zhdFLVgzwkW3ItovhbjSN8',
    appId: '1:620043907346:ios:c7f67d95cf23b7ba8843cb',
    messagingSenderId: '620043907346',
    projectId: 'flutter-test-3a45f',
    storageBucket: 'flutter-test-3a45f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
